language: perl
sudo: false

perl:
  - "5.24"
  - "5.26"
  - "5.28"

before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .
  - cover -delete
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
